name: bt_terminal
description: A Bluetooth Terminal app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.31.16
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"        # путь к вашей иконке
  adaptive_icon_background: "#FFFFFF"           # фон для Android adaptive icon (можно цвет или изображение)
  #adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"  # передний план (опционально)

flutter:
  uses-material-design: true